# Generated by Django 4.2.6 on 2023-11-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_lesson_course_payment'),
        ('users', '0002_remove_user_username_user_avatar_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='lms.course', verbose_name='курсы пользователя'),
        ),
        migrations.AddField(
            model_name='user',
            name='lessons',
            field=models.ManyToManyField(related_name='students', to='lms.lesson', verbose_name='уроки пользователя'),
        ),
    ]
