# слева хостовые данные - справа контейнерные

version: '3'
services:
  db: # неважно как называть
    image: postgres
    environment:
#      POSTGRES_PASSWORD: mysecret
#      PGDATA: /var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=mysecret
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - PGUSER=postgres

    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata  # чтобы не терялись данные БД при перезапуске
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d lmsdocker -U postgres" ]   # "pg_isready -d db-name -U db-user"
      interval: 10s
      timeout: 5s
      retries: 5

  app: # неважно как называть
    build: .
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000 # порты здесь для возм-ти доступа внутрь контейнера
#    volumes: # для сохранения изменений? стыкуем локальную папку с папкой code
#      - .:/code
    ports:
      - '8001:8000'
    depends_on:
      db:
        condition: service_healthy
#    depends_on: # зависимость от готовности БД, но иногда БД не успевает прогрузить поэтому используем healthcheck
#      - db

volumes:
  pg_data: