# Generated by Django 4.2.6 on 2023-11-11 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_alter_subscription_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='user',
            new_name='owner',
        ),
    ]
