# Generated by Django 4.2.6 on 2023-11-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_rename_user_subscription_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_link',
            field=models.CharField(max_length=1000, null=True, verbose_name='ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(default='pending', max_length=200, verbose_name='статус оплаты'),
        ),
    ]
