# Generated by Django 4.2.6 on 2023-11-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_payment_payment_link_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_session_stripe_id',
            field=models.CharField(max_length=200, null=True, verbose_name='сессия stripe'),
        ),
    ]
